[ids]
REPLACE_WITH_KEYD_MONITOR_ID

[main]
capslock = overload(capslock, esc)

[capslock:C]
h = left
j = down
k = up
l = right
leftbrace = G-leftbrace
semicolon = G-semicolon
apostrophe = G-apostrophe
