return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-debug-adapter",
      "bash-language-server",
      "copilot-language-server",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "firefox-debug-adapter",
      "go-debug-adapter",
      "gofumpt",
      "goimports",
      "gopls",
      "html-lsp",
      "jq",
      "js-debug-adapter",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "mdx-analyzer",
      "shfmt",
      "stylua",
      "svelte-language-server",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
